version: '3'

services:

  platform_outgoing_api:
    build: ./platform_out/
    entrypoint: ['/project/entrypoint.sh']
    command: python manage.py run -h 0.0.0.0
    volumes:
      - ./platform_out/:/project/
    ports:
      - 5000:5000
    environment:
      - FLASK_APP=app/__init__.py
      - FLASK_ENV=development
      - APP_SETTINGS=app.config.DevelopmentConfig
      - DATABASE_URL=postgresql://postgres:postgres@platform-db:5432/fvh_db_dev   
      - DATABASE_TEST_URL=postgresql://postgres:postgres@platform-db:5432/fvh_db_test
      - SQL_HOST=platform-db
      - SQL_PORT=5432
      - DATABASE=postgres 
    depends_on:   
      - platform-db

  platform-db:
    build:
        context: ./platform_out/db
        dockerfile: Dockerfile
    #volumes:
     #   - postgres_data:/var/lib/postgresql/data/
    expose:
        - 5432
    environment:
        - POSTGRES_USER=postgres
        - POSTGRES_PASSWORD=postgres

volumes:
  postgres_data: