version: '3'

services:

  platform_outgoing_api:
    build: 
        context: ./platform_out/
        dockerfile: Dockerfile.prod
    entrypoint: ['/project/entrypoint.sh']
    command: gunicorn --bind 0.0.0.0:5000 manage:app
    volumes:
      - ./platform_out/:/project/
    expose:
      - 5000
    #env_file:
    #  - kafka-variables.env
    environment:
      - FLASK_APP=app/__init__.py
      - FLASK_ENV=development
      - APP_SETTINGS=app.config.DevelopmentConfig
      - DATABASE_URL=postgresql://postgres:postgres@platform-db:5432/fvh_db_dev   
      - DATABASE_TEST_URL=postgresql://postgres:postgres@platform-db:5432/fvh_db_test
      - SQL_HOST=platform-db
      - SQL_PORT=5432
      - DATABASE=postgres 
    depends_on:   
      - platform-db
      - redis

  platform-db:
    build:
        context: ./platform_out/db
        dockerfile: Dockerfile
    volumes:
        - postgres_data:/var/lib/postgresql/data/
    expose:
        - 5432
    environment:
        - POSTGRES_USER=postgres
        - POSTGRES_PASSWORD=postgres
        
  nginx:
    build: ./nginx
    ports:
      - 1337:80
    depends_on:
      - platform_outcoming_api

volumes:
  postgres_data: